version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: zenphoto_db
      MYSQL_USER: zenphoto_user
      MYSQL_PASSWORD: secret_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"


  zenphoto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      ZENPHOTO_DB_HOST: mysql
      ZENPHOTO_DB_NAME: zenphoto_db
      ZENPHOTO_DB_USER: zenphoto_user
      ZENPHOTO_DB_PASSWORD: secret_password
    volumes:
      - .:/var/www/html

volumes:
  mysql_data:
